#! /usr/bin/env bash

if [[ `lsmod | grep kvm_intel | wc -l` -ge 1 ]] ; then
	echo 'Ok, kvm_intel loaded already'
else
	echo 'Running: sudo modprobe kvm_intel'
	sudo modprobe kvm_intel
	echo 1 | sudo tee /sys/kernel/mm/ksm/run > /dev/null
fi

if [ "$(cat /sys/kernel/mm/ksm/run || echo 1)" -eq "0" ] ; then
    # https://wiki.archlinux.org/title/QEMU#Tips_and_tricks
    echo "Enabling kernel same-page merging"
    echo 1 | sudo tee /sys/kernel/mm/ksm/run > /dev/null
fi

qemu-system-x86_64 -enable-kvm -machine type=pc \
-cpu host -smp 2 \
-m 4096 -device virtio-balloon \
-vga qxl \
-usb -device usb-tablet \
-boot d -cdrom "$@"

#-usbdevice tablet -soundhw ac97 \
#-vga vmware \
#-localtime
