#! /usr/bin/env bash

if [[ `lsmod | grep kvm_intel | wc -l` -ge 1 ]] ; then
	echo 'Ok, kvm_intel loaded already'
else
	echo 'Running: sudo modprobe kvm_intel'
	sudo modprobe kvm_intel
	echo 1 | sudo tee /sys/kernel/mm/ksm/run > /dev/null
fi


qemu-system-x86_64 -enable-kvm -machine type=pc,accel=kvm \
-cpu host \
-localtime -boot d -m 1024 -cdrom $*

#-usbdevice tablet -soundhw ac97 \
#-vga vmware \
