#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

DAEMON=sshproxy

EXE='/usr/bin/ssh'
OPTS='-Y -o ServerAliveInterval=60 -Nfg'

[ -r /etc/conf.d/$DAEMON ] && . /etc/conf.d/$DAEMON

if [[ $SUDOUSER == "" || $SERVER == "" || $PORT == "" ]]; then
	echo "Put config in /etc/conf.d/$DAEMON"
	exit 1
fi

PID=$(ps aux | grep ssh | grep -- "$SERVER" | grep -- "$OPTS" | grep -- "$PORT" | awk '{print($2);}')

case "$1" in
	status)
		#stat_busy "Checking $daemon_name status";
		#ck_status $daemon_name
		if [ -z "$PID" ]; then
			# -z doesn't exist
			# -n exists
			echo "$DAEMON is not running"
		else
			echo "$DAEMON is running"
		fi
	;;
	start)
		need_root
		stat_busy "Starting $DAEMON"
		[ -z "$PID" ] && sudo -u dmn $EXE $SERVER $OPTS -D '*:'$PORT &>/dev/null
		if [ $? = 0 ]; then
			add_daemon $DAEMON
			stat_done
		else
			stat_fail
			exit 1
		fi
	;;
	stop)
		need_root
		stat_busy "Stopping $DAEMON"
		[ -n "$PID" ] && kill $PID &>/dev/null
		if [ $? = 0 ]; then
			rm_daemon $DAEMON
			stat_done
		else
			stat_fail
			exit 1
		fi
	;;
	restart)
		$0 stop
		sleep 1
		$0 start
	;;
	*)
		echo "usage: $0 {start|stop|restart|status}"
esac

