#! /bin/bash

## by dmn, http://devsite.pl

if [[ $1 != "" ]]; then
	DEVICES="`mount | grep $1 | awk '{print($1);}' | sed 's/[1-9]//'`"
	if [[ $DEVICES != "" ]]; then
		echo "Unmounting ${DEVICES}:"
		mount | grep ${DEVICES}
		sudo umount ${DEVICES}*
	else
		echo "Device $1 is not mounted"
		exit 2
	fi
else
	echo "`basename $0` [device]"
	exit 1
fi
### su -c 'umount /media/truecrypt1 && truecrypt -d && rm -rf /tmp/.truecrypt_aux_mnt1/'
